### ISSUE TITLE
Doesn't work on 6.72

### ISSUE THREAD

**Issue by Frank-sudoapt** [Zer0xFF/PS4_db_rebuilder#11]
Hi i tried this tool on 6.72 but it doesn't work. It gives me an error: cursor.execute("INSERT INTO %s VALUES %s;" % (tbl[0], ', '.join(sql_list)))
sqlite3.OperationalError: table tbl_appbrowse_0349983844 has 53 columns but 47 values were supplied. How can i solve this problem? Thx

**Comment by cichazosia2001** [comment]
https://github.com/Zer0xFF/PS4_db_rebuilder/issues/8

**Comment by Zer0xFF** [comment]
as noted, this is a duplicate of #8, check that issue out please
