### ISSUE TITLE
Not working with extended storage

### ISSUE THREAD

**Issue by lnsfrht** [Zer0xFF/PS4_db_rebuilder#2]
Hi first thank you for your script it worked with games installed on internal Drive however it didn't scan games and homebrews installed on the extended hard drive i tried to change the path to /mnt/ext0/user/app on your script it listed the games fine but stopped with ftplib.error 550 file not found i'm not a python developer and i do not know how the ps4 app.db should be to rebuild it correctly can you guide me please?
I have an other issue with your script the games restaured to the db do not appear in the storage list "applications" something is missing?

**Comment by Zer0xFF** [comment]
Hi, Thanks for opening this issue.

unfortunately I don't use an external hdd for my game storage (well, I barely have any games installed at the moment), so I dont really know how games are stored and listed.

if you have basic knowledge of ftp, I'd advise you to find the hdd, and explore it, try to find if there is a database file on the hdd, if you find it, post it here, try to find `param.sfo` note its location, then perhaps I can do an experimental "build" for you to test.

**Comment by lnsfrht** [comment]
Hi thank you for responding i had changed few things "paths" in your script last night after posting the issue here it's listing apps and inserting rows to the sqllite file app.db but visibly I missed something because the games shows as corrupted and no image anyway here is a link to Dropbox for the ruined script with screen shots https://www.dropbox.com/sh/v8k0bdhe0fbw86q/AABt6CXUUKO6Is0uop5s0NVza?dl=0
Thank you for your help

**Comment by lnsfrht** [comment]
New update after rebuilding the PS4 db with safe mode menu I've reinstalled the apps in the internal hard drive because the apps we're not appearing in hdd application list,after that I remounted the external hard drive to backup the games on that disk an icon of hdd appearing on the top left screen the games installed are back
I don't know how and why it is behaving like this but everything is back to normal maybe somebody will find this useful thanks again for your time and for sharing your valuable script
Have a great day

**Comment by 5p0k** [comment]
> New update after rebuilding the PS4 db with safe mode menu I've reinstalled the apps in the internal hard drive because the apps we're not appearing in hdd application list,after that I remounted the external hard drive to backup the games on that disk an icon of hdd appearing on the top left screen the games installed are back
> I don't know how and why it is behaving like this but everything is back to normal maybe somebody will find this useful thanks again for your time and for sharing your valuable script
> Have a great day

hi please can you provide a short tutorial how you restored data from external drive without reinstall?

**Comment by lnsfrht** [comment]
All what I did is loading hen  plugging the HDD ensure it's online in extended storage wait few moments the icon will appear on the top right of the screen the PS4 will rescan the entire hard drive and add the games to the home screen

**Comment by thxalot60** [comment]
Here is the 0.1 rebuilder designed to run for external only. I did not combine it into the current rebuilder script. You can restore internal and then external or vice versa. Just run exactly as you would the internal.
[release_0.1 EXTERNAL.zip](https://github.com/Zer0xFF/PS4_db_rebuilder/files/3843961/release_0.1.EXTERNAL.zip)

**Comment by 5p0k** [comment]
thanks both - all works after restart so you saved me days or weeks of redownloading and reinstalling :)

however the code still needs to be fixed since games on internal are disappearing from storage menu :(

**Comment by Darkregs** [comment]
Fix For 6.72 with ext Hdd https://www1.zippyshare.com/v/6PuAMAIG/file.html

@Zer0xFF you can renew your code with this fix bro, make two code option, with ext and int hdd

**Comment by ghostdarkblade** [comment]
Hi All, Thanks for the provided tools and tips!! I managed to restore my games on internal hd but I cannot on the external hdd. I used the provided release.0.1.EXTERNAL.zip to execute in CMD. See below: 
`AppData\Local\Programs\Python\Python38-32>py fix_db.py 192.168.18.13
["'CUSA02980'", "'CUSA07378'", "'CUSA00030'", "'CUSA05839'", "'CUSA07792'", "'CUSA04104'", "'CUSA07828'", "'CUSA06090'", "'CUSA00062'", "'CUSA05848'", "'CUSA00135'", "'CUSA05952'", "'CUSA03454'", "'CUSA00528'", "'CUSA01126'", "'CUSA04135'", "'CUSA04692'", "'CUSA00371'", "'CUSA00491'", "'CUSA07023'", "'CUSA05588'", "'CUSA06067'", "'CUSA03679'", "'CUSA00775'", "'CUSA05485'", "'CUSA04530'", "'CUSA02092'", "'CUSA02646'", "'CUSA01123'", "'CUSA00000'", "'CUSA00740'", "'CUSA04622'", "'CUSA01867'", "'CUSA03012'", "'CUSA05670'", "'CUSA01344'", "'CUSA00242'", "'CUSA02057'", "'CUSA02976'", "'CUSA03641'", "'CUSA11228'", "'CUSA03312'", "'CUSA02532'", "'CUSA02882'", "'CUSA05486'", "'CUSA09172'", "'CUSA03048'", "'CUSA05827'", "'CUSA09920'", "'CUSA04107'", "'CUSA00265'", "'CUSA02353'", "'CUSA01319'", "'CUSA06886'", "'CUSA00628'", "'CUSA00329'", "'CUSA00498'", "'CUSA09461'", "'CUSA01836'", "'CUSA03551'", "'CUSA03558'", "'CUSA03506'", "'CUSA01345'", "'CUSA06701'", "'CUSA02762'", "'CUSA04768'", "'CUSA00320'", "'CUSA01991'", "'CUSA00910'", "'CUSA06915'", "'CUSA00503'", "'CUSA03992'", "'CUSA08364'", "'CUSA04529'", "'CUSA03979'", "'CUSA03512'", "'CUSA03522'", "'CUSA07569'", "'CUSA03144'", "'CUSA05598'", "'CUSA00773'", "'CUSA00168'", "'CUSA01009'", "'CUSA02924'", "'CUSA00460'", "'CUSA07865'", "'CUSA01004'", "'CUSA04607'", "'CUSA05133'", "'CUSA03991'", "'CUSA01493'", "'CUSA09565'", "'CUSA00194'", "'CUSA03499'", "'CUSA06994'", "'CUSA01210'", "'CUSA01433'", "'CUSA06244'", "'CUSA04097'", "'CUSA00230'", "'CUSA01857'", "'CUSA04282'", "'CUSA02974'", "'CUSA08251'", "'CUSA04893'", "'CUSA00176'", "'CUSA00009'", "'CUSA09682'", "'CUSA01073'", "'CUSA02377'", "'CUSA03220'", "'CUSA00002'", "'CUSA01715'", "'CUSA03487'", "'CUSA00004'", "'CUSA00063'", "'CUSA07632'", "'CUSA09243'", "'CUSA06638'", "'CUSA04770'", "'CUSA05170'", "'CUSA02769'", "'CUSA06740'", "'CUSA03880'", "'CUSA04548'", "'CUSA06702'", "'CUSA05531'", "'CUSA01400'", "'CUSA04814'", "'CUSA06712'", "'CUSA02348'", "'CUSA02586'", "'CUSA01875'", "'CUSA08877'", "'CUSA07399'", "'CUSA36666'", "'CUSA11120'", "'CUSA03509'", "'CUSA04811'", "'CUSA05032'", "'CUSA02344'", "'CUSA03617'", "'CUSA06086'", "'CUSA03951'", "'CUSA07188'", "'CUSA03397'", "'CUSA06253'", "'CUSA05275'", "'CUSA00382'", "'CUSA00557'", "'CUSA00109'", "'CUSA04437'", "'CUSA08366'", "'CUSA00038'", "'CUSA02094'", "'CUSA00593'", "'CUSA04013'", "'CUSA02231'", "'CUSA00044'", "'CUSA00293'", "'CUSA03888'", "'CUSA09991'", "'CUSA10484'", "'CUSA10940'", "'CUSA15937'", "'CUSA09171'", "'CUSA11379'", "'CUSA08025'", "'CUSA11626'", "'CUSA02299'", "'CUSA08519'", "'CUSA10300'", "'CUSA14876'", "'CUSA13689'", "'CUSA08548'", "'CUSA09303'", "'CUSA08154'", "'CUSA08518'", "'CUSA11115'", "'CUSA12145'", "'CUSA09559'", "'CUSA10646'", "'CUSA10777'", "'CUSA04932'", "'CUSA06569'", "'CUSA08161'", "'CUSA11650'", "'CUSA12941'", "'CUSA13643'", "'CUSA14032'", "'CUSA11898'", "'CUSA07202'", "'CUSA15322'", "'CUSA14974'"]
Processing table: tbl_appbrowse_0370220361
        Processing GameID: CUSA00000... Completed 44695552
        Processing GameID: CUSA00002... Completed 40301101056
        Processing GameID: CUSA00004... Completed 23806345216
        Processing GameID: CUSA00009... Completed 20601176064
        Processing GameID: CUSA00030... Completed 4723638272
        Processing GameID: CUSA00038... Completed 842530816
        Processing GameID: CUSA00044... Completed 6207963136
        Processing GameID: CUSA00062... Completed 2168717312
        Processing GameID: CUSA00063... Completed 14317912064
        Processing GameID: CUSA00109... Completed 19929104384
        Processing GameID: CUSA00135... Completed 48974594048
        Processing GameID: CUSA00168... Completed 13939507200
        Processing GameID: CUSA00176... Completed 2314403840
        Processing GameID: CUSA00194... Completed 37961662464
        Processing GameID: CUSA00230... Completed 5106106368
        Processing GameID: CUSA00242... Completed 29822943232
        Processing GameID: CUSA00265... Completed 185991168
        Processing GameID: CUSA00293... Completed 283639808
        Processing GameID: CUSA00320... Completed 45193953280
        Processing GameID: CUSA00329... Completed 4862771200
        Processing GameID: CUSA00371... Completed 388562944
        Processing GameID: CUSA00382... Completed 224395264
        Processing GameID: CUSA00460... Completed 8666087424
        Processing GameID: CUSA00491... Completed 301793280
        Processing GameID: CUSA00498... Completed 4136239104
        Processing GameID: CUSA00503... Completed 44119490560
        Processing GameID: CUSA00528... Completed 161742848
        Processing GameID: CUSA00557... Completed 41722249216
        Processing GameID: CUSA00593... Completed 12409896960
        Processing GameID: CUSA00628... Completed 7014187008
        Processing GameID: CUSA00740... Completed 104988672
        Processing GameID: CUSA00773... Completed 928120832
        Processing GameID: CUSA00775... Completed 130088960
        Processing GameID: CUSA00910... Completed 4788584448
        Processing GameID: CUSA01004... Completed 17534222336
        Processing GameID: CUSA01009... Completed 4729339904
        Processing GameID: CUSA01073... Completed 27477344256
        Processing GameID: CUSA01123... Completed 2521694208
        Processing GameID: CUSA01126... Completed 1244725248
        Processing GameID: CUSA01210... Completed 3637575680
        Processing GameID: CUSA01319... Completed 3717005312
        Processing GameID: CUSA01344... Completed 287375360
        Processing GameID: CUSA01345... Completed 8791523328
        Processing GameID: CUSA01400... Completed 3118530560
        Processing GameID: CUSA01433... Completed 1450639360
        Processing GameID: CUSA01493... Completed 38489030656
        Processing GameID: CUSA01715... Completed 41722707968
        Processing GameID: CUSA01836... Completed 39042416640
        Processing GameID: CUSA01857... Completed 117506048
        Processing GameID: CUSA01867... Completed 137363456
        Processing GameID: CUSA01875... Completed 3853516800
        Processing GameID: CUSA01991... Completed 1835401216
        Processing GameID: CUSA02057... Completed 993394688
        Processing GameID: CUSA02092... Completed 47059501056
        Processing GameID: CUSA02094... Completed 12386762752
        Processing GameID: CUSA02231... Completed 20240138240
        Processing GameID: CUSA02299... Completed 43521671168
        Processing GameID: CUSA02344... Completed 43569643520
        Processing GameID: CUSA02348... Completed 127467520
        Processing GameID: CUSA02353... Completed 391118848
        Processing GameID: CUSA02377... Completed 38840172544
        Processing GameID: CUSA02532... Completed 2858156032
        Processing GameID: CUSA02586... Completed 2603089920
        Processing GameID: CUSA02646... Completed 1161428992
        Processing GameID: CUSA02762... Completed 8222539776
        Processing GameID: CUSA02769... Completed 23614783488
        Processing GameID: CUSA02882... Completed 25800605696
        Processing GameID: CUSA02924... Completed 3425763328
        Processing GameID: CUSA02974... Completed 4229562368
        Processing GameID: CUSA02976... Completed 6516899840
        Processing GameID: CUSA02980... Completed 31858294784
        Processing GameID: CUSA03012... Completed 161021952
        Processing GameID: CUSA03048... Completed 3006529536
        Processing GameID: CUSA03144... Completed 4792713216
        Processing GameID: CUSA03220... Completed 42994696192
        Processing GameID: CUSA03312... Completed 3409641472
        Processing GameID: CUSA03397... Completed 15292628992
        Processing GameID: CUSA03454... Completed 173539328
        Processing GameID: CUSA03487... Completed 237699072
        Processing GameID: CUSA03499... Completed 10504568832
        Processing GameID: CUSA03506... Completed 3158769664
        Processing GameID: CUSA03509... Completed 2982739968
        Processing GameID: CUSA03512... Completed 2161573888
        Processing GameID: CUSA03522... Completed 47246278656
        Processing GameID: CUSA03551... Completed 2868576256
        Processing GameID: CUSA03558... Completed 2210660352
        Processing GameID: CUSA03617... Completed 46030848000
        Processing GameID: CUSA03641... Completed 38068092928
        Processing GameID: CUSA03679... Completed 40233598976
        Processing GameID: CUSA03880... Completed 28962848768
        Processing GameID: CUSA03888... Completed 9512091648
        Processing GameID: CUSA03951... Completed 28962848768
        Processing GameID: CUSA03979... Completed 28002746368
        Processing GameID: CUSA03991... Completed 16043212800
        Processing GameID: CUSA03992... Completed 9279045632
        Processing GameID: CUSA04013... Completed 34198650880
        Processing GameID: CUSA04097... Completed 1018167296
        Processing GameID: CUSA04104... Completed 2208301056
        Processing GameID: CUSA04107... Completed 1887305728
        Processing GameID: CUSA04135... Completed 701759488
        Processing GameID: CUSA04282... Completed 848953344
        Processing GameID: CUSA04437... Completed 16600662016
        Processing GameID: CUSA04529... Completed 47596896256
        Processing GameID: CUSA04530... Completed 20330971136
        Processing GameID: CUSA04548... Completed 8533508096
        Processing GameID: CUSA04607... Completed 19415564288
        Processing GameID: CUSA04622... Completed 4052484096
        Processing GameID: CUSA04692... Completed 237305856
        Processing GameID: CUSA04768... Completed 4530438144
        Processing GameID: CUSA04770... Completed 1441464320
        Processing GameID: CUSA04811... Completed 2899705856
        Processing GameID: CUSA04814... Completed 824377344
        Processing GameID: CUSA04893... Completed 40122974208
        Processing GameID: CUSA04932... Completed 23660265472
        Processing GameID: CUSA05032... Completed 4149280768
        Processing GameID: CUSA05133... Completed 23830921216
        Processing GameID: CUSA05170... Completed 1773993984
        Processing GameID: CUSA05275... Completed 38119079936
        Processing GameID: CUSA05485... Completed 15003877376
        Processing GameID: CUSA05486... Completed 31869829120
        Processing GameID: CUSA05531... Completed 40554004480
        Processing GameID: CUSA05588... Completed 975241216
        Processing GameID: CUSA05598... Completed 5039259648
        Processing GameID: CUSA05670... Completed 23869194240
        Processing GameID: CUSA05827... Completed 3960209408
        Processing GameID: CUSA05839... Completed 1247936512
        Processing GameID: CUSA05848... Completed 27715043328
        Processing GameID: CUSA05952... Completed 4011917312
        Processing GameID: CUSA06067... Completed 346161152
        Processing GameID: CUSA06086... Completed 1177157632
        Processing GameID: CUSA06090... Completed 2041839616
        Processing GameID: CUSA06244... Completed 1435893760
        Processing GameID: CUSA06253... Completed 5338759168
        Processing GameID: CUSA06569... Completed 38088605696
        Processing GameID: CUSA06638... Completed 19400753152
        Processing GameID: CUSA06701... Completed 8420327424
        Processing GameID: CUSA06702... Completed 2969567232
        Processing GameID: CUSA06712... Completed 1052704768
        Processing GameID: CUSA06740... Completed 22761701376
        Processing GameID: CUSA06886... Completed 2625896448
        Processing GameID: CUSA06915... Completed 12906332160
        Processing GameID: CUSA06994... Completed 6364659712
        Processing GameID: CUSA07023... Completed 194248704
        Processing GameID: CUSA07188... Completed 13510508544
        Processing GameID: CUSA07202... Completed 36038705152
        Processing GameID: CUSA07378... Completed 46591508480
        Processing GameID: CUSA07399... Completed 22717267968
        Processing GameID: CUSA07569... Completed 25124798464
        Processing GameID: CUSA07632... Completed 6683885568
        Processing GameID: CUSA07792... Completed 4274192384
        Processing GameID: CUSA07828... Completed 5076942848
        Processing GameID: CUSA07865... Completed 11338317824
        Processing GameID: CUSA08025... Completed 38002819072
        Processing GameID: CUSA08154... Completed 7034568704
        Processing GameID: CUSA08161... Completed 31592611840
        Processing GameID: CUSA08251... Completed 30587355136
        Processing GameID: CUSA08364... Completed 15644360704
        Processing GameID: CUSA08366... Completed 10312876032
        Processing GameID: CUSA08518... Completed 30909595648
        Processing GameID: CUSA08519... Completed 85467529216
        Processing GameID: CUSA08548... Completed 11374428160
        Processing GameID: CUSA08877... Completed 4970184704
        Processing GameID: CUSA09171... Completed 23200202752
        Processing GameID: CUSA09172... Completed 16864313344
        Processing GameID: CUSA09243... Completed 23306240000
        Processing GameID: CUSA09303... Completed 44225593344
        Processing GameID: CUSA09461... Completed 36468162560
        Processing GameID: CUSA09559... Completed 21541879808
        Processing GameID: CUSA09565... Completed 2968715264
        Processing GameID: CUSA09682... Completed 28197584896
        Processing GameID: CUSA09920... Completed 433586176
        Processing GameID: CUSA09991... Completed 4262199296
        Processing GameID: CUSA10300... Completed 31428575232
        Processing GameID: CUSA10484... Completed 588972032
        Processing GameID: CUSA10646... Completed 1203306496
        Processing GameID: CUSA10777... Completed 38813237248
        Processing GameID: CUSA10940... Completed 2498035712
        Processing GameID: CUSA11115... Completed 13973127168
        Processing GameID: CUSA11120... Completed 2627796992
        Processing GameID: CUSA11228... Completed 33210630144
        Processing GameID: CUSA11379... Completed 39994785792
        Processing GameID: CUSA11626... Completed 2680553472
        Processing GameID: CUSA11650... Completed 611057664
        Processing GameID: CUSA11898... Completed 19006685184
        Processing GameID: CUSA12145... Completed 5573509120
        Processing GameID: CUSA12941... Completed 712966144
        Processing GameID: CUSA13643... Completed 2805202944
        Processing GameID: CUSA13689... Completed 20592394240
        Processing GameID: CUSA14032... Completed 9917759488
        Processing GameID: CUSA14876... Completed 13817085952
        Processing GameID: CUSA14974... Completed 359530496
        Processing GameID: CUSA15322... Completed 3764322304
        Processing GameID: CUSA15937... Completed 14731182080
        Processing GameID: CUSA36666... Completed 184090624
Traceback (most recent call last):
  File "fix_db.py", line 90, in <module>
    cursor.execute("INSERT INTO %s VALUES %s;" % (tbl[0], ', '.join(sql_list)))
sqlite3.OperationalError: table tbl_appbrowse_0370220361 has 53 columns but 47 values were supplied`

**Comment by ghostdarkblade** [comment]
Just deleted my post. Darkregs thanks so much for this it worked for me!!!!! you made my day.

update on this: games arent working for me it says" Cannot start application. The data is corrupted"

**Comment by mvergaraq** [comment]
Any news on this solution? All the games on my external hdd are gone :'(
